#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V

bspc config border_width         1
bspc config window_gap           12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#Autostart
feh --bg-scale --randomize /home/ikari/Imágenes/Fondos/* &
$HOME/.config/polybar/launch.sh
/usr/bin/lxpolkit &
xsetroot -cursor_name left_ptr
compton --config ~/.config/compton/compton.conf &
setxkmap es &
